### PR TITLE
Fix conversion from null to integer

### PR DESCRIPTION
**Pull request by okaufmann**
The property of min_disk_size could be null, if so use default value of 0

### CODE REVIEW

**Comment by okaufmann** [comment]
Maybe someone shoul test the schema of the digitalocean json responses against your services with some unit tests ?

**Comment by yassirh** [comment]
I'm not sure on which case would min_disk_size be null? having a fall back value doesn't hurt so thank you. as of testing the services that is something on my check list :)

**Comment by okaufmann** [comment]
I noticed this in the returned json when I analysed the response coming from DO. There the property "min_disk_size" was null. Either this is a bug of the DO Api or a documentation failure... Or it can really be null don't know...

But due to in the app this property is nowhere showed or used it really doesn't matter, doesn't it?

Your welcome happy to can give a little bit back for your work.

**Comment by yassirh** [comment]
If you get a null it must be documentation issue :)

**Comment by okaufmann** [comment]
When will you release a new version with the bugfixes on the play store?

**Comment by yassirh** [comment]
This weekend. if you want a daily build go here : https://yassirh.com/digitalocean_swimmer/releases/

**Comment by okaufmann** [comment]
Just asked out of sheer curiosity :smile: I still have the working version from debugging sessions with android studio. When you released a new version I woll change to the play version to get automatic updates. Just need a working version of your great app ;)

**Pull request merged**
